version: '3'

x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./ETL:/opt/spark/ETL
    - ./dags:/opt/spark/dags
    - ./download:/opt/spark/download
  networks:
    - airflow-network
    
x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./ETL:/opt/airflow/ETL
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./download:/opt/airflow/download
  depends_on:
    - postgres
  networks:
    - airflow-network

services:
  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_MASTER_URL= spark://spark-master:7077

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - airflow-network

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname test --lastname test --role Admin --email test@test.com --password admin && airflow scheduler"

networks:
  airflow-network: